/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import data.Player;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author wilder-eb
 */
public class GUI extends javax.swing.JFrame implements UI {

    private String defaultInfoMessage = "BIENVENIDO A UN POKERINHO";
    
    public GUI() {
        try {

            initComponents();

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

            SwingUtilities.updateComponentTreeUI(this);
            
            this.pack();
            this.setVisible(true);
            
        }
         catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException exception) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, exception);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void printWelcome() {

    }

    @Override
    public void printMainMenu(Player player) {

    }

    @Override
    public void printInstructions() {

    }

    @Override
    public void printCards(Player player) {

    }

    @Override
    public void printNewCards(Player player) {

    }

    @Override
    public void printCredits(Player player) {

    }

    @Override
    public void printCategorizeHand(Player player) {

    }

    @Override
    public void printSaved() {

    }

    @Override
    public void printLoaded() {

    }

    @Override
    public void printError(String error) {

    }

    @Override
    public String askName() {
        return "a";
    }

    @Override
    public int askMenuOption() {
        return 1;
    }

    @Override
    public int askBetAmount(Player player) {
        return 1;
    }

    @Override
    public int[] askReject() {
        int[] reject = {0, 0, 0, 0, 0};
        return reject;
    }

    @Override
    public boolean printGameOver() {
        return true;
    }
}
